README.md
服务器位于大陆时的一些问题及解决方案
github.com的源加速方案不是百分百可靠，会有检测，默认的curl脚本不会跟着302，wget没有问题，可以考虑使用wget解决
```bash
root@cc-zhenjiang-ct:~# curl -L https://hub.fastgit.org/naiba/nezha/releases/latest/download/nezha-agent_linux_amd64.tar.gz
<html><meta charset="utf-8" /><title>检测中</title><div>跳转中</div></html>
<script> window.location.href ="/naiba/nezha/releases/download/v0.1.9/nezha-agent_linux_amd64.tar.gz?btwaf=68873680"; </script>
```
=> 服务器位于大陆时的一些问题及解决方案

service/monitor/monitor.go
当机器中存在多个挂载点时，原先的代码只会统计`/`挂载点的使用情况。
如图所示：
此PR修复了这一问题。
=> fix: correct minor typos in disk usage statistic

.gitignore, resource/static/theme-hotaru/css/darkmode.css, resource/template/theme-hotaru/home.html
=> 新增手动修改白天/黑夜模式

README.md, script/install.sh
* 加强了中国大陆安装时候的稳定性和安装速度
* 将raw.sevencdn.com替换为cdn.jsdelivr.net
* 由于FastGit不支持对Release中非源码的加速下载，更换为DaoCloud提供的镜像
* 将中国大陆的Docker安装脚本更换为DaoCloud提供的镜像安装脚本，同时指定阿里源为Docker源(对Centos无效)
* 增加了对中国大陆安装IP的判断
* 修改了README中对镜像安装脚本的介绍
=> 加强了中国大陆安装时候的稳定性和安装速度

.github/workflows/dashboard.yml, script/docker-compose.yaml, script/install.sh
Actions推送到阿里云上海仓库 && 安装脚本修改
注意:
* 最好是阿里云上海，Github的Action运行环境是美国Azure，走上海联通去阿里云上海推送很快，换区域需要修改，push上去大概10M
* 命名空间和名称均已经写死
* secrets.ALI_PAT和secrets.ALI_USER需要自行设置
* jsdelivr的缓存刷新提交后大概需要15分钟才会在网宿的边缘节点生效
* 缓存刷新那边处理了小写是因为我用户名是大写的 方便测试干脆一起处理下小写
* 国内安装源会从阿里云上海拉取镜像
=> Actions推送到阿里云上海仓库 && 安装脚本修改

cmd/agent/monitor/monitor.go
流量统计排除了内网，docker等并没有生效，看了下是包含的顺序不对
=> 解决排除网卡不生效的bug

cmd/agent/monitor/monitor.go
在LXC容器中
mem.SwapMemory() 函数返回的是宿主机的Swap信息
mem.VirtualMemory() 函数返回错误的Used值为32EB
另: mem.VirtualMemory()函数已经返回了正确的Swap信息
=> 修复LXC容器的读取内存和Swap错误

README.md, cmd/agent/main.go
使用 nginx 配置 SSL/TLS证书反代 grpc 连接，需要使用 grpc TLS安全连接。如需开启Cloudflare CDN，需要在Cloudflare域名管理网络中开启gRPC。
=> agent 增加 SSL/TLS 选项

README.md, cmd/agent/main.go, cmd/dashboard/main.go, cmd/dashboard/rpc/rpc.go, model/config.go, model/monitor.go, resource/template/component/server.html, resource/template/dashboard/server.html, script/install.sh
您好，前些天我提供了反代 gRPC 的方法。但是后来发现因为 Nginx 或者 Cloudflare 的一些限制。如果面板和服务器的 ServerStream 连接长时间没有数据传输，Nginx 或者 Cloudflare 会断开连接，从而导致 Agent 监控端与面板服务器的 gRPC 连接频繁断开重连，导致面板内存占用一直增高。我做了一些修改，面板每隔一段时间（目前设置的60秒）会向所有服务器发送一次数据来保持连接不被断开，经过测试目前没有出现 Nginx 或者 Cloudflare 超时时间限制导致的重连问题了。我也对前端和脚本做了一些修改，以方便使用反代 gRPC 时生成一键安装命令安装 Agent 监控端。
=> :sparkles: 反向代理 gRPC 端口（支持 Cloudflare CDN）

.goreleaser.yml, README.md, script/install.sh
为Agent添加更多架构支持
S390X已测试(IBM LinuxONE) 除CPU名称无法获取外均正常
RISCV64未测试
=> Agent支持IBM-S390X和RISCV64架构

cmd/agent/monitor/monitor.go, go.mod, go.sum
说人话就是在支持的Linux下大幅降低统计TCP/UDP连接数资源消耗
=> Add SS Func to accelerate connections count in some Linux

README.md, model/rule.go, resource/template/theme-mdui/viewpassword.html, service/dao/alertsentinel.go
月流量报警
- type
- transfer_in_cycle 周期内的入站流量
- transfer_out_cycle 周期内的出站流量
- transfer_all_cycle 周期内双向流量和
- cycle_start 统计周期开始日期（可以是你机器计费周期的开始日期），RFC3339时间格式，例如北京时间为`2022-01-11T08:00:00.00+08:00`
- cycle_interval 每隔多少个周期单位（例如，周期单位为天，该值为7，则代表每隔7天统计一次）
- cycle_unit 统计周期单位，默认`hour`,可选(`hour`, `day`, `week`, `month`, `year`)
- min/max、cover、ignore 参考基本规则配置
- 示例: ID 为 3 的机器（ignore 里面定义）的每月 15 号计费的出站月流量 1T 报警 `[{"type":"transfer_out_cycle","max":1000000000000,"cycle_start":"2021-07-15T08:00:00+08:00","cycle_interval":1,"cycle_unit":"month","cover":1,"ignore":{"3":true}}]`
- [![7QKaUx.md.png](https://s4.ax1x.com/2022/01/13/7QKaUx.md.png)](https://imgtu.com/i/7QKaUx)
=> 添加统计周期单位cycle_unit

cmd/dashboard/controller/member_api.go, model/monitor.go
由于后台管理页面提交新的服务时，初始化`Monitor`没有给`SkipServers`赋值，而`Monitor`的AfterFind仅在数据库做查询动作时才更新，而该动作仅在整个程序初始化才会做查询动作，导致新增服务的`SkipSevers`一直为`nil`.
https://github.com/naiba/nezha/blob/3144620a1599fc33a9b05f94c61b5c9e329ca696/cmd/dashboard/controller/member_api.go#L225-L259
而到了执行任务时，由于`task.SkipServers`实际为`nil`，导致在MonitorCoverIgnoreAll时进入了条件语句，跳出循环，导致没有执行任务。
https://github.com/naiba/nezha/blob/3144620a1599fc33a9b05f94c61b5c9e329ca696/cmd/dashboard/rpc/rpc.go#L47-L51
=> 修复管理后台页面新添加CoverIgnoreAll类型服务需要重启docker镜像的问题.

README.md, cmd/dashboard/controller/member_api.go, model/notification.go, resource/static/main.css, resource/static/main.js, resource/template/common/footer.html, resource/template/common/header.html, resource/template/component/notification.html, service/singleton/singleton.go
在通过通知的方式调用第三方WebAPI时
若该API请求体需要对有效的服务器状态指标（如IP）进行验证
可能会返回非200状态码并将阻止添加/修改该通知方式
因此在添加/修改通知方式界面添加一个checkbox
勾选后本次添加/修改将不发送测试信息
具体用例：
当希望通过IP变更通知提醒报警 将服务器IP添加至Cloudflare Access Rule 白名单时
需要先创建对应的通知方式进行相关API请求
若IP无效 Cloudflare API 会返回400状态码
此时无法保存该新建的通知方式
因此需要跳过测试信息发送
=> feat: 添加/修改通知方式时可选择不发送测试信息

README.md, service/singleton/api.go, service/singleton/singleton.go
last_active 可用于判断服务器当前是否在线
表示上次向面板汇报时间的unix时间戳
下面示例中的负数时间戳为（0000-00-00）
目前表示面板上线后该服务器从未汇报过状态
但不建议用正负性判断状态
`GET /api/v1/server/list`
```
{
"code": 0,
"message": "success",
"result": [
{
"id": 1,
"name": "t1",
"tag": "222",
"last_active": 1653014667,
"ipv4": "1.1.1.1",
"ipv6": "",
"valid_ip": "1.1.1.1"
},
{
"id": 2,
"name": "22",
"tag": "111",
"last_active": -62135596800,
"ipv4": "",
"ipv6": "",
"valid_ip": ""
}
]
}
```
`GET /api/v1/server/details?id=&tag=`
```
{
"code": 0,
"message": "success",
"result": [
{
"id": 1,
"name": "t1",
"tag": "222",
"last_active": 1653015042,
"ipv4": "1.1.1.1",
"ipv6": "",
"valid_ip": "1.1.1.1",
"host": {
"Platform": "darwin",
"PlatformVersion": "12.3.1",
"CPU": [
"Apple M1 Pro 1 Physical Core"
],
"MemTotal": 17179869184,
"DiskTotal": 2473496842240, …
```
=> update: 服务器状态API增加上次汇报时间的unix时间戳

resource/template/common/header.html, resource/template/theme-default/service.html
**请勿合并此代码，仅作效果参考**
本人能力有限，简单用js撸了一个流量剩余显示的功能，我认为这样显示的话更美观方便（如图）
移动设备参考图：
再次重复，请勿合并此代码，这种实现方式太不美观了，只是能用，连我自己都看不下去。。。。。希望作者大大能考虑开发此功能，后端实现的话应该会好很多。
至于改了header，是因为需要增添一个meta告知手机浏览器不要把数字识别为手机号，否则js会运行错误。
=> 默认主题增加流量剩余显示

cmd/dashboard/controller/controller.go, resource/template/theme-default/service.html
增加流量剩余显示的详细剩余流量
改进CSS，优化显示效果（包括流量当小于50%，20%，和耗尽时，进度条的颜色随之改变）
=> 流量剩余显示增加详细信息

cmd/dashboard/controller/oauth2.go
匹配新版本go-GitHub包的变更。
手动创建API Client以绕过NewEnterpriseClient内强制添加的/api/v3/路径
=> fix: Gitee login error

script/entrypoint.sh
sh下echo -e实际会输出带有"-e"的首行
使得首个nameserver无效
```shell
sh-3.2$ echo -e "nameserver 127.0.0.11\nnameserver 8.8.4.4\nnameserver 223.5.5.5\n" > test.txt
sh-3.2$ cat test.txt
-e nameserver 127.0.0.11
nameserver 8.8.4.4
nameserver 223.5.5.5
```
改用printf后
```shell
sh-3.2$ printf "nameserver 127.0.0.11\nnameserver 8.8.4.4\nnameserver 223.5.5.5\n" > test.txt
sh-3.2$ cat test.txt
nameserver 127.0.0.11
nameserver 8.8.4.4
nameserver 223.5.5.5
```
详情见下面链接
https://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo
=> fix: nameserver issue

cmd/agent/monitor/monitor.go
常规状态汇报时使用缓存的bootTime
但是如果这个缓存的bootTime不为0
（部分环境存在系统启动时间错误的问题，需要等待网络时间同步服务更新正确的时间）
那么每10分钟的系统信息更新不会更新这个缓存
就导致虽然第10分钟那一次汇报会给面板上报正确的时间
但是下一次常规汇报又回回到错误的时间
每10分钟进行一次的unix时间戳转换与boottime读取并不会占用过多资源。
因此本pr将不再判断bootTime不为0，总是向缓存写入最新的数据
=> fix: 部分环境下启动时间锁定在1970年的问题

script/install.sh, script/install_en.sh
Arch 的官方源中不含有`yay`，安装脚本亦没有检查`base-devel`包和`git`包是否存在，在新安装系统中使用此脚本会造成错误。正确方法是克隆仓库后使用`makepkg`安装`libselinux`及其依赖。
=> 修正 Arch 的安装错误

script/install_en.sh
效仿中文版shell给英文版shell增加中国IP判断
缘由：个人使用英文版的面板，但有插探针到中国地区服务器的需求，此时哪吒的一键脚本使用的```install_en.sh```没有配置中国IP检测，导致无法安装监控端。
修改部分：效仿中文版shell给英文版shell增加中国IP判断，但默认如果检测不到是中国IP时不使用中国镜像仍使用原始的Github链接，仅这部分不同。
=> 效仿中文版shell给英文版shell增加中国IP判断

cmd/dashboard/controller/member_api.go, model/monitor.go, resource/l10n/zh-CN.toml, resource/static/main.js, resource/template/component/monitor.html, resource/template/dashboard-default/monitor.html, service/singleton/alertsentinel.go, service/singleton/notification.go, service/singleton/servicesentinel.go
-  最近30点位服务状态由「正常」变更为「低可用」「故障」时触发故障任务
-  最近30点位服务状态由「低可用」「故障」变更为「正常」时触发恢复任务
对于「由触发服务器执行」的任务
触发服务器为 使服务状态发生变更的上报 所使用的服务器
例如：
服务器A的任务上报使得最近30点位服务状态由「正常」变为「低可用」
则触发故障任务，触发服务器为「服务器A」
=> Feat: 服务监控支持触发任务执行

service/rpc/nezha.go, service/singleton/alertsentinel.go, service/singleton/notification.go, service/singleton/servicesentinel.go
同 #288 对服务器监控的静音缓存改动， 服务状态变更时清除静音缓存，防止状态变更通知无法发送
解决下面这个问题
```
2023/06/18 04:05:09 在线率 100
2023/06/18 04:05:10 在线率 83
2023/06/18 04:05:10 NEZHA>> 尝试通知 tg1
2023/06/18 04:05:10 NEZHA>> 向  tg1  发送通知成功：
2023/06/18 04:05:11 在线率 71
2023/06/18 04:05:11 NEZHA>> 静音的重复通知： [故障] cc Reporter: 测试1, Error: Get "http://127.0.0.1:17878": dial tcp 127.0.0.1:17878: connect: connection refused bf::ssc-1:1
2023/06/18 04:05:14 在线率 80
2023/06/18 04:05:14 NEZHA>> 静音的重复通知： [故障] cc Reporter: 测试2, Error:  bf::ssc-1:1
2023/06/18 04:05:15 在线率 81
2023/06/18 04:05:15 NEZHA>> 静音的重复通知： [低可用] cc Reporter: 测试1, Error:  bf::ssc-1:1
2023/06/18 04:05:40 在线率 96
2023/06/18 04:05:40 NEZHA>> 静音的重复通知： [良好] cc Reporter: 测试2, Error:  bf::ssc-1:1
```
修复后：
```
2023/06/18 04:10:39 在线率 100
2023/06/18 04:10:40 在线率 75
2023/06/18 04:10:40 …
```
=> 服务状态变更时清除静音缓存

script/install.sh
get.daocloud.io is down. Use origin url instead.
=> Fix: get.daocloud.io 503

script/install.sh, script/install_en.sh
If entered with install_agent argument, variable IS_DOCKER_NEZHA will not be set, thus leading select menu to appear, which could be annoying.
=> Exit after installing agent

model/notification.go, pkg/utils/http.go
我有点被绕糊涂了，是不是原来的逻辑反了，当 verifySSL 的值为 true 时 InsecureSkipVerify 应该为 false，但是在原来的代码中为 true
https://github.com/naiba/nezha/blob/3059bf2d49effd78a1dfa1480d9035a487626b8d/model/notification.go#L116-L122
=> fix: field name "VerifySSL" to "SkipVerifySSL" in Transport config

script/install.sh, script/install_en.sh
original script can only check if 'docker' command exists, but not 'docker compose'.
=> installer: fix docker compose command determination

Dockerfile
By using the Alpine image, the image size has been reduced from 80MB to approximately 22MB. I have tested it on linux/amd64, and it runs smoothly. If Nezha does not have dependencies on the ubuntu-focal environment, using Alpine is a better choice.
=> Improve: use alpine as dockerfile base image

script/install.sh, script/install_en.sh
更新判断逻辑，否则会出现
这种报错
因为之前有使用docker安装，所以肯定会存在对应的容器镜像，检测这个更保险一些
=> 更新判断面板是否是通过docker安装的逻辑

cmd/dashboard/controller/api_v1.go, cmd/dashboard/controller/common_page.go, cmd/dashboard/controller/member_api.go, cmd/dashboard/rpc/rpc.go, model/config.go, model/monitor.go, model/monitor_history.go, resource/l10n/en-US.toml, resource/l10n/es-ES.toml, resource/l10n/zh-CN.toml, resource/l10n/zh-TW.toml, resource/template/common/menu.html, resource/template/theme-daynight/home.html, resource/template/theme-daynight/network.html, resource/template/theme-daynight/service.html, resource/template/theme-default/network.html, resource/template/theme-server-status/content-nav.html, resource/template/theme-server-status/header.html, resource/template/theme-server-status/network.html, service/singleton/api.go, service/singleton/servicesentinel.go, service/singleton/singleton.go
大佬，这个 mr 是面板新增 ping 历史趋势图的改动：
1. 新增网络监控页面
2. 新增接口指定 server_id 查询监控历史
3. 下发 Task 逻辑上做了变更，覆盖所有时，指定的 server 为不下发，其余都下发
4. proto 部分 task 新增 server_id 字段用于识别监控记录是哪个server ping 的
麻烦帮忙看看这样设计 和 编码是否合理 Orz
具体效果大概这样的[https://tz.181000.xyz/network](https://tz.181000.xyz/network)
=> feat: add network monitor hitory

cmd/dashboard/controller/common_page.go, resource/template/theme-daynight/service.html, resource/template/theme-default/service.html, resource/template/theme-server-status/service.html
主要改动点：
1. revert 主题 `service.html` 中的变更
2. 在后端 `/service` 中提前判断是否需要展示，返回给前端的数据，全部都拿来展示，避免每个主题都需要适配
=> fix: revert service html and block service in backend

model/monitor_history.go
改动：
1. 删除无用代码
2. 在下面这个查询中会使用到`server_id、monitor_id、created_at`， 实际select会多一个`avg_delay`字段，因此考虑直接添加覆盖索引避免回表查询
3. 因为 created_at 字段在 common 里面不太好加覆盖索引，因此把里面的字段直接复制了出来添加索引（这个我这没找到太好的方法）
```
DB.Model(&model.MonitorHistory{}).Select("monitor_id, created_at, server_id, avg_delay").
Where(query).Where("created_at >= ?", time.Now().Add(-24*time.Hour)).Order("monitor_id, created_at").
Scan(&monitorHistories).Error
```
=> feat: add index on monitor history

model/config.go, resource/template/theme-default/network.html
修复/美化了以下问题：
- 延迟默认最高300ms，超过后默认抹平
- 曲线上有很多ping值为0的无效散点，导致毛刺很多，干扰效果
- 图标的y轴比例失调，上方大片留白，大大降低了有效显示区域
- 默认只显示最近不到半小时左右的延迟表现，想看全天需要拖动，影响效果
- 曲线不显示极大极小值，不够直观
=> 对历史延迟图表进行了相关修复/美化工作

resource/template/theme-mdui/menu.html, resource/template/theme-mdui/network.html
修改：
- menu.html：增加了“网络”选项卡，图标是 `network_check`。
增加：
- network.html：参照默认主题写了一个适配 Mdui 主题的页面，国旗显示参照 `home.html` 使用 `flag-icons` 库的 svg。
可能存在的问题：
1. “网络”的图标如果有更好看的可以改成别的；
2. 部分朋友反应颜色过于鲜艳，可以再改改颜色。
=> 增加了网络页面对 Neko Meui 主题的支持

README.md, script/install.sh, script/install_en.sh
使用useradd -m创建的用户会产生主目录文件夹，使用userdel需要添加-r参数
=> Arch 修复 nezha-agent 主目录遗留问题

resource/template/theme-daynight/network.html, resource/template/theme-default/network.html, resource/template/theme-mdui/network.html
更改：
1. theme-daynight 的默认最大 TCPing 从 300 更为 1000，与 theme-default 统一；
2. 删去各模板设置的 echarts 布局最大宽度（95vw），改为使用 grid 设置 echarts 左右空白各 8% 实现居中。
增加：
1. 增加 echarts 宽度自适应功能，当屏幕宽度改变（例如：横屏切换为竖屏）时自动重新设置 echarts 宽度。
=> 网络监控页面相关优化

cmd/dashboard/controller/member_api.go, model/server.go, resource/l10n/en-US.toml, resource/l10n/es-ES.toml, resource/l10n/zh-CN.toml, resource/l10n/zh-TW.toml, resource/static/main.js, resource/template/common/footer.html, resource/template/component/server.html, resource/template/dashboard-default/server.html, resource/template/theme-angel-kanade/footer.html, service/rpc/nezha.go
在服务器后台管理界面增加了每个服务器只更新ipv4或ipv6的选项，更改后需要同时勾选启用DDNS和DDNS ipv4或ipv6两个选项才能使DDNS生效（三个都选也可以，即和之前的效果一样）
=> ddns: Add ability to update IPv4 or IPv6 only

resource/template/theme-server-status/header.html, resource/template/theme-server-status/home.html
1. ServerStatus主题integrity方式JS引入错误
2. 修复点击点亮的地图时，弹出文案中英文区分未生效bug
=> 修复ServerStatus主题Bug

cmd/dashboard/controller/guest_page.go, cmd/dashboard/controller/oauth2.go, model/config.go, pkg/oidc/cloudflare/cloudflare.go
示例配置：
Admin:  ZeroTrust-MyTeam-Users-<具体用户>-UserID
ClientID与ClientSecret获取方式: ZeroTrust-Access-Applications-SaaS-OIDC
```yaml
Oauth2:
Admin: 701b9ea6-9f56-48cd-af3e-cbb4bfc1475c
ClientID: 3516291f53eca9b4901a01337e41be7dc52f565c8657d08a3fddb2178d13c5bf
ClientSecret: 0568b67c7b6d0ed51c663e2fe935683007c28f947a27b7bd47a5ad3d8b56fb67
Endpoint: "https://akkia.cloudflareaccess.com"
Type: cloudflare
```
=> :sparkles: 支持cloudflare access OIDC认证

script/install.sh, script/install_en.sh
在使用 Arch 安装 `libsepol` 和 `libselinux` 包时，当前脚本中的 GPG 公钥 `BE22091E3EF62275` 已不可用。本 PR 将公钥更新为 `4695881C254508D1`。
已在本地测试，确保安装过程顺利完成。
```
==> 正在使用 gpg 验证源文件签名...
libsepol-3.6.tar.gz ... 失败 (未知的公钥 4695881C254508D1)
==> 错误： 一个或多个 PGP 签名无法校验！
```
=> Update GPG key for libsepol

.github/workflows/release.yml, .github/workflows/test-on-pr.yml, .github/workflows/test.yml, script/install_en.sh
使用 go 内置的 `time/tzdata` 包提供时区信息，以避免安装额外的 `tzdata` 依赖包，并解决 Windows 默认没有内置时区数据导致无法启动 Dashboard 的问题。
=> ci: using time/tzdata package to provide zoneinfo

resource/template/theme-default/home.html
前台温度选项默认显示简化信息（只显示cpu），点击之后将切换显示详细温度信息。
单板机的温度传感器名称都不一样，我只加了rockchip和allwinner的（其它的我手上没有），如果检测不到预设名称的话就取温度最大值。
现在这个版本大部分是@nap0o写的
切换前：
切换后：
=> Add option to reduct temperature information

service/singleton/server.go
为游客隐藏了DDNS域名信息，DDNS域名对一些人来说属于敏感信息，并可能泄漏机器ip，所以不应该被游客访问
=> Hide DDNS domain info for guests

cmd/dashboard/controller/common_page.go, service/singleton/server.go
~直接操作DDNSDomain看来是不行，等以后找到合适的方法再改吧，只能建议现在不要用ddns功能，一定要用的话把游客隐藏打开~
=> Temporary fix for DDNSDomain leaks

resource/template/theme-angel-kanade/home.html, resource/template/theme-default/home.html, resource/template/theme-server-status/home-group-false.html, resource/template/theme-server-status/home-group-true.html, resource/template/theme-server-status/home.html
=> 优化gpu前端展示代码

model/rule.go, service/singleton/singleton.go
- 将流量循环中的时间都转换为了UTC时间，以处理时区问题（gorm进行where查询时不会带`time.Time`的时区信息）
- 将流量记录打点时间中的时区替换为了本地时区
=> fix: timestamp conversion

model/monitor.go, pkg/websocketx/safe_conn.go
`conn.WriteMessage` is not thread-safe itself, hence adding a write lock to prevent concurrent write.
Other fixes:
- fix `monitor.IsServiceSentinelNeeded` logic (renamed TaskTypeTerminal to TaskTypeTerminalGRPC, as the former is deprecated)
Tested on my own machine and a team member's.
=> fix: concurrent write to single WebSocket connection

script/install.command, script/install.sh, script/install_en.sh
The install scripts previously used ipapi.co to determine if the user's IP was located in China. This commit changes the service to ipinfo.io, updating the curl commands and printed messages accordingly. This should improve geographical accuracy when determining whether to use a Chinese mirror for installation.
=> Update IP location service in install scripts

resource/template/dashboard-default/server.html, script/install.sh, script/install_en.sh
使用了和agent相同的4个geoip api来判断位置，以防止只有一个时出现rate limit导致获取不了位置的情况
另删掉了复制一键脚本命令中冗余的sudo
=> installer: use multiple geoip api to determine location

script/install.ps1
使用Cloudflare CDN判断地理位置从而选择下载服务器
之前所使用的属地API在国内无法连接，更换为Cloudflare CDN节点可以避免这个问题
- https://dash.cloudflare.com/cdn-cgi/trace
- https://cf-ns.com/cdn-cgi/trace
- https://1.0.0.1/cdn-cgi/trace
使用了全球Anycast、国内京东云合作多条线路，避免因网络连通性问题导致获取不了位置的情况
实测效果：
=> installer: improve region detection reliability using CDN APIs

service/singleton/api.go
给v1 api加了DisplayIndex信息，第三方程序在服务器排序时需要用到
=> api: add DisplayIndex info

resource/template/theme-angel-kanade/home.html
=> chore: missing gpu info line break in theme-angel-kanade

model/server.go
在ws返回的json数据中忽略所有DDNS相关字段（大部分时间并不需要）
=> ws: ignore all DDNS fields

resource/static/manifest-en-US.json, resource/template/theme-default/header.html, resource/template/theme-default/home.html, resource/template/theme-default/network.html, resource/template/theme-server-status/header.html
1.补上上个pr误删的网页title
2.修复network页纵坐标数值显示不全
3.修复network，多个legend导致的遮挡主图表问题，默认设置为，
移动端：每2个legend元素增加28px
pc端： 每6个元素增加34px
修改默认设置的方法，后台设置，增加自定义代码
```
<script>
localStorage.setItem("maxLegendsPerRowPc", 4); //pc端设置为每4个legend元素增加28px
localStorage.setItem("maxLegendsPerRowMobile", '3');  //移动端设置为每3个legend元素增加28px
</script>
```
演示地址： https://dev.nezha.pp.ua/network
=> Default主题fixbug

resource/static/theme-default/js/mixin.js, resource/static/theme-server-status/css/main.css, resource/template/theme-default/header.html, resource/template/theme-default/menu.html, resource/template/theme-default/network.html, resource/template/theme-server-status/header.html, resource/template/theme-server-status/home-group-false.html, resource/template/theme-server-status/home-group-true.html, resource/template/theme-server-status/home.html, resource/template/theme-server-status/network.html
1.增加点击图表标题快速切换下一个监测项目
2.增加图表数据加载时loading效果
3.修复深色/浅色模式切换时，图表获取数据可能出现的id错误问题
4.用动态定义1vh基准的方法解决移动端各种机型与各种浏览器高度不一直导致的图表高度不同问题
5.当发生绝对丢包时,只显示markline丢包线
6.修复default主题network页因legend图例过多导致时间缩放条被隐藏不显示问题。
7.一些其他小优化
演示地址： https://dev.nezha.pp.ua/network
=> improve: status-server主题network页

cmd/dashboard/controller/controller.go, go.mod, go.sum, model/config.go, model/notification.go, pkg/ddns/cloudflare.go, pkg/ddns/ddns.go, pkg/ddns/tencentcloud.go, pkg/utils/gjson.go, pkg/utils/hfs.go, resource/resource.go, service/rpc/nezha.go
更改：
- 自定义主题与内置主题共用 `/static`，优先读取内置主题的文件
- 根据 `resource/template/theme-custom/theme.json` 识别自定义主题，并自动加入后台主题列表
- 部分json数据获取操作替换为 `gjson` 以提高性能
描述文件示例：
```json
{
"name": "Example",
"description": "An example theme",
"maintainer": "Noname <example@example.com>",
"repo": "https://example.com/example.git",
"version": "0.0.1",
"support_versions": "^0.19.0"
}
```
其中面板只用到了 name，其它字段的目的是为了增加拓展性（比如给第三方程序使用）
=> feat: description file for custom theme; use gjson

cmd/dashboard/controller/member_api.go, model/config.go, pkg/ddns/ddns.go, pkg/utils/utils.go, resource/l10n/en-US.toml, resource/l10n/es-ES.toml, resource/l10n/zh-CN.toml, resource/l10n/zh-TW.toml, resource/template/dashboard-default/setting.html, service/singleton/ddns.go
查询操作如果成功一般并不会执行到ipv6的情况，加了ipv6还会导致单栈机器直接返回，故删除
在配置文件中加入自定义DNS服务器字段，格式为 `1.1.1.1:53,8.8.8.8:53...`
=> ddns: remove ipv6 nameservers, support custom nameservers

cmd/dashboard/controller/controller.go, cmd/dashboard/controller/ddns.go, cmd/dashboard/controller/member_api.go, cmd/dashboard/controller/member_page.go, model/ddns.go, service/singleton/ddns.go
用于前端获取DDNS提供商列表，
另把`DDNSProfile.Provider`改回字符串，避免再加新的接口去传键值对
增加json标签
=> ddns: add listProviders api

go.mod, go.sum, service/singleton/ddns.go
Since `github.com/libdns/tencentcloud` isn’t compatible with other `libdns` implementations (https://github.com/libdns/tencentcloud/issues/1), and the project seems unmaintained, we’ll need to implement a compatible one ourselves.
=> ddns: replace tencentcloud implemention

cmd/dashboard/main.go
This PR separates "showing version" from the entire program.
According to the original code, running "./dashboard -v" will produce the following errors:
```
panic: open data/config.yaml: no such file or directory
goroutine 1 [running]:
github.com/naiba/nezha/service/singleton.InitConfigFromPath(...)
github.com/naiba/nezha/service/singleton/singleton.go:49
main.init.0()
github.com/naiba/nezha/cmd/dashboard/main.go:37 +0x20b
```
In Go, the `init()` will run before the `main()`, and some codes in `init()` initialize the service. Therefore, we can check the version flag in the init stage, and after the version is displayed, the program exits.
=> fix(cli): display version without initializing app

.github/workflows/release.yml, .github/workflows/sync-release.yml
goreleaser 给arm64路径也加上版本号了，文件夹有个扩展名`.0`，导致zip文件创建在错误路径，这里改为只处理basename
=> ci: fix arm64 path parsing

.github/workflows/release.yml, README.md, resource/template/component/server.html, resource/template/dashboard-default/server.html, script/install.sh, script/install_en.sh
修复没给程序权限问题
将脚本后续更新地址改到 <https://github.com/nezhahq/scripts>，之后脚本在那里维护了，不在这里改了
gitee还没有同步仓库，可以先看下 https://github.com/nezhahq/scripts/pull/1
=> ci: fix permission when packaging; move installer to another repository

.dockerignore, Dockerfile.dev, cmd/dashboard/controller/api_v1.go, docker-compose.yml, service/singleton/api.go
1. add 1 POST endpoints `/api/v1/server/register`
2. add `docker-compose.yml` and `Dockerfile.dev` for developing
POST data format
```json
{
"name": "abcd",
"Tag": "",
"Note": "",
"HideForGuest": "on"
}
```
You can post a empty data `{}`, then it will use the default data
```
name=$IP
Tag="AutoRegister"
Note=""
HideForGuest="on"
```
If it contain query `simple=1` or `simple=true`, it will only return a secret string. Otherwise It return json
```json
{
"code":200,
"message":"Server created successfully",
"secret":"8GYwaxYuLfU7zl7ndC"
}
```
1. without `simple`
```bash
➜  ~ curl -X POST http://127.0.0.1:18080/api/v1/server/register \ 
-H "Content-Type: application/json" \
-H "Authorization: POXbxorKJBM8wPMKX8r2PdMblyXvpggB" \
-d '{
"name": "curl",
"Tag": "",
"Note": "",
"HideForGuest": "on" …
```
=> Add API to register server

cmd/dashboard/controller/controller.go
Fixes [https://github.com/nezhahq/nezha/security/code-scanning/23](https://github.com/nezhahq/nezha/security/code-scanning/23)
To fix the problem, we need to validate the user input before using it to construct a file path. We should ensure that the resolved path is within a specific safe directory. This can be done by resolving the input with respect to that directory and then checking that the resulting path is still within it.
1. Define a constant for the safe directory.
2. Resolve the user-provided path with respect to the safe directory.
3. Check that the resolved path is within the safe directory.
4. If the path is valid, proceed with the file operations; otherwise, return an error.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 23: Uncontrolled data used in path expression

script/entrypoint.sh
- Replace direct command execution with exec to make app PID 1
- Ensures proper signal propagation in container
- Follows container best practices for process management
=> fix: use exec to properly handle container signals

cmd/dashboard/controller/controller.go, cmd/dashboard/controller/jwt.go, cmd/dashboard/controller/oauth2.go, cmd/dashboard/controller/user.go, go.mod, go.sum, model/oauth2bind.go, model/user.go, model/user_api.go, pkg/i18n/template.pot
1. strings.ToLower 延后到更新数据库条目时调用
2. callback 和 bind api 使用对应的 redirect url
Fix https://github.com/nezhahq/nezha/issues/928
=> fix: oauth2 redirect url not consistent

cmd/dashboard/controller/controller.go, cmd/dashboard/controller/jwt.go, model/config.go
新增 `forceauth` 选项，只能手动配置。
开启后，所有访客 API（例如查看服务器，在线用户等）均需要强制认证，登录相关 API 不受影响。
=> feat: option to force authorization for vistor routes

cmd/dashboard/controller/server.go, model/server.go, model/server_api.go, pkg/ddns/ddns.go, service/rpc/nezha.go
`Server` 新增 `OverrideDDNSDomains` 字段，可以覆盖使用的 DDNS 配置的域名。
=> ddns: allow overriding domains per configuration

cmd/dashboard/controller/oauth2.go, model/oauth2bind.go
Fix https://github.com/nezhahq/nezha/issues/1000
=> fix: possible redirect url inconsistency

.goreleaser.yml, cmd/dashboard/controller/controller.go, cmd/dashboard/controller/fm.go, cmd/dashboard/controller/jwt.go, cmd/dashboard/controller/server.go, cmd/dashboard/controller/service.go, cmd/dashboard/controller/setting.go, cmd/dashboard/controller/terminal.go, cmd/dashboard/controller/ws.go, cmd/dashboard/main.go, cmd/dashboard/rpc/rpc.go, go.mod, go.sum, model/alertrule.go, model/common.go, model/config.go, model/cron.go, model/ddns.go, model/notification.go, model/server.go, model/service.go, model/setting_api.go, model/waf.go, pkg/utils/gjson.go, pkg/utils/koanf.go, pkg/utils/utils.go, pkg/utils/utils_test.go, service/singleton/alertsentinel.go, service/singleton/user.go
- `http.Server` 已经支持 HTTP/2 PRI, 不再需要使用 h2c 库
- 将 `jsoniter` 替换为目前仍在维护的 `goccy/go-json`
- 支持 HTTPS，可以用于一些特殊场景（比如 Cloudflare Tunnel 需要 HTTPS 才能处理 h2）
- 配置字段支持下划线格式
- 翻新一些语法
=> feat: update to go1.24 & support listening https

cmd/dashboard/main.go, model/user.go, pkg/utils/utils.go, service/singleton/user.go
Since the `agent_secret` field in configuration is not exposed anymore and should be deprecated, now generates a key for users that who lacks `agent_secret` in their profile (usually seen in older installations)
=> generate agent_secret for old users

cmd/dashboard/controller/controller.go, cmd/dashboard/controller/setting.go, cmd/dashboard/controller/user.go, cmd/dashboard/rpc/rpc.go, model/config.go, model/user.go, model/user_api.go, service/singleton/alertsentinel.go
现在管理员创建的服务与告警规则覆盖范围可包括所有用户资源，而普通用户创建的服务与告警规则不再对管理员用户的资源生效。
Fix https://github.com/nezhahq/nezha/issues/1112
=> fix: member-created services shouldn't be applied to admin resources
