nezhahq/nezha

README.md

自定义版权去除jq引用，添加wxpush示例

---

cmd/dashboard/controller/member_api.go
model/server.go
resource/template/component/server.html
resource/template/dashboard/server.html
resource/template/theme-default/home.html

添加标签功能，默认主题可根据标签分组

---

resource/template/theme-default/home.html

调整状态卡片上下空白高度

---

resource/static/theme-hotaru/css/darkmode.css

🌈 Change background color.

---

.github/workflows/dashboard.yml
cmd/dashboard/controller/common_page.go

* WebSocket增加Ping包，避免出现长时间无交互消息被断开情况
* Actions构建镜像时用户名转为小写，避免出现 [repository name must be lowercase](https://github.com/Erope/nezha/runs/2260599012?check_suite_focus=true) 错误

WebSocket增加Ping包 & Actions构建镜像时用户名转为小写

---

README.md

增加了 Daylight 主题 更改进度条颜色 和 版权示例的代码

更新 README.md 使用文档

---

script/install.sh

借用jsdelivr获取版本号

---

.github/workflows/dashboard.yml
README.md
script/install.sh

面板安装支持ARM和x86
* 为Action使用QEMU构建ARM和x86的image

面板安装支持ARM和x86

---

cmd/dashboard/controller/member_api.go

复现步骤：
1.后台管理->资产，添加服务器
2.保存之后，再编辑密钥，该密钥无法使用
问题：
编辑时，dao.SecretToID这个map没有同步修改

修复修改密钥后，agent连不上bug

---

README.md

Add OpenWRT_Nezha Project

---

cmd/dashboard/controller/controller.go
resource/template/theme-mdui/home.html

Round check next time format to second

---

cmd/agent/main.go
cmd/agent/monitor/monitor.go
cmd/dashboard/controller/oauth2.go
model/cron.go

schame(schema) -> scheme : 基于RFC3986

fix some typo

---

cmd/dashboard/controller/common_page.go

WriteMessage 方法会自动创建messageWriter对象
因此可以直接用该方法写数据而不需要手动创建

optimise: 优化websocket数据包发送逻辑 加快首次访问时监控信息载入速度

---

README.md
model/notification.go
resource/template/component/notification.html
service/singleton/singleton.go

#SERVER.TCPCONNCOUNT#
#SERVER.UDPCONNCOUNT#

update: 增加TCP连接数与UDP连接数的占位符

---

README.md
model/notification.go
resource/template/component/notification.html
service/singleton/singleton.go

#SERVER.IP#
#SERVER.IPV4#
#SERVER.IPV6#

update: #SERVER.IP#仅返回一个IP(优先返回ipv4地址)｜ 新增获取ipv4与ipv6地址的占位符

---

script/install.ps1

使用https://api.myip.com/ 无CF检查
$region -eq $null 暂未遇见,暂留

😉新增region判断

---

script/install_en.sh

Translate the installation script

Translate the installation script

---

resource/l10n/en-US.toml
resource/template/dashboard/monitor.html
resource/template/dashboard/setting.html
resource/template/theme-daynight/home.html
resource/template/theme-default/home.html
resource/template/theme-hotaru/home.html
resource/template/theme-mdui/home.html

英语版本中的天翻译成了Day，实际上，大部分情况下显示的天数都应该为复数

修改了一些文本和格式错误

---

resource/template/component/server.html
resource/template/dashboard/server.html

update: 使用 "ServerGroup" 标签在服务器相关页面

---

resource/template/dashboard/server.html

fix: 恢复错误修改的Tag

---

README.md
script/install.sh
script/install_en.sh

Add SELinux Check
No work for Arch

Add SELinux Check

---

README.md
script/install.sh
script/install_en.sh

Fix SELinux for more system

---

script/install.ps1

tls spport for Windows installer

Add tls support

---

script/install.sh
script/install_en.sh

Add update before fetch

---

resource/template/dashboard/server.html

删除多余}  水pr=,=

---

.github/workflows/dashboard.yml
script/install.sh

JSdelivr -> Jihulab

---

README.md
resource/template/common/footer.html
service/singleton/singleton.go

Fix 修改main.js的版本参数避免缓存问题

---

README.md
script/install.sh
script/install_en.sh

修改面板配置时不直接修改

---

README.md
script/install.sh
script/install_en.sh

Add timeout limit for wget

---

README.md
resource/template/dashboard-default/server.html
service/singleton/singleton.go

一键脚本语言跟随面板语言

---

resource/template/dashboard-default/server.html

fix 未能创建 SSL/TLS 安全通道

---

script/install.ps1

replace ghproxy to dn-dao-github-mirror.daocloud.io
revised some tips

limit ps version

---

resource/template/common/footer.html
resource/template/common/header.html
resource/template/dashboard-default/server.html
resource/template/theme-daynight/home.html
resource/template/theme-daynight/service.html
resource/template/theme-hotaru/home.html
resource/template/theme-mdui/home.html
resource/template/theme-mdui/service.html
resource/template/theme-mdui/viewpassword.html

更改前端库，xterm没有找到合适的替代方案，维持原字节CDN

Change bytecdntp to staticfile

---

.goreleaser.yml

Add FreeBSD Agent For Goreleaser

Add FreeBSD Agent For Goreleaser

---

resource/template/theme-default/home.html

[bug in pic](https://s2.loli.net/2022/08/26/26Q5FYibzwKvVjP.png)

fixArchLinuxIcon

---

resource/template/dashboard-default/server.html

服务器备注支持换行显示

---

script/install.sh

更好的支持archlinux

---

script/install_en.sh

Fix non-arch system execution installation arch system related software errors Fix the problem that the created user has login permissions, etc.

Fix fatal permission issue

---

.github/workflows/dashboard.yml

Revert "Feat: Add jsdelivr purge step in workflow"

---

cmd/dashboard/main.go

增加了一些命令行参数。
虽然flag.Parse()放在init会有点儿奇怪，不过放在main会干扰初始化，还是放在init了。

Feat: Add some parameters

---

script/install.sh
script/install_en.sh

已测试。
1.安装或者修改 Agent ，菜单选项8和9，增加询问是否开启 --tls，默认不开启
2.Alpine 也能像其他系统一样，支持使用 ./nezha.sh install_agent agent.nezha.com 443 Uw9yL7GVSfM4y23X5l --tls 来开启 --tls
3.删除了脚本中不必要的空格

 [agent] Alpine 系统增加 SSL/TLS加密 (--tls) 支持。

---

resource/l10n/en-US.toml
resource/l10n/es-ES.toml
resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml

优化繁体中文、英语、西班牙语语言文件，与中文语言文件保持一致

优化繁体中文、英语、西班牙语语言文件

---

script/nezha-agent

alpine在自动更新agent以后不会自动重启agent，导致批量掉线，添加守护进程以后问题解决

add supervise daemon for alpine

---

resource/static/theme-default/css/main.css
resource/template/theme-default/home.html

修改国旗图标为4*3的大国旗
解决卡片头因服务器名字过长而错位

修改default主题

---

script/install.sh
script/install_en.sh
script/nezha-agent
script/nezha-dashboard

修复了安装脚本在Alpine上无法正常使用Docker安装的问题，并增加了OpenRC查看日志的功能，修改了脚本中重复的部分

fix installer bugs & improve

---

script/install.sh
script/install_en.sh

fix: EUID is a readonly variable on some shells

---

resource/static/theme-server-status/js/mixin.js
resource/template/theme-server-status/header.html
resource/template/theme-server-status/service.html

1. 如果后台没有配置服务监控，前台增加提示
2. initData方法从go模版语言转为vue模版语言
3. 优化getDayTails方法,控制数字最多显示小数点后3位

优化server-status主题服务页

---

model/rule.go

为GPU与温度添加告警支持，
其中温度只检测最大值
如果温度项不存在则直接返回nil
如果GPU使用率值为-1且 `LastActive` 时间不为0且版本号大于等于 `0.17.0`，则直接返回nil

feat: notifications support for GPU & Temperature

---

pkg/ddns/cloudflare.go
pkg/ddns/dummy.go
pkg/ddns/tencentcloud.go
pkg/ddns/webhook.go
service/singleton/ddns.go

ddns: improve performance

---

script/install.command
script/install.ps1
script/install.sh
script/install_en.sh

installer: restore the China mirror of agent

---

resource/static/theme-server-status/css/dark.css
resource/static/theme-server-status/css/main.css
resource/template/theme-server-status/content-footer.html
resource/template/theme-server-status/header.html
resource/template/theme-server-status/home.html

1. echart图表透明背景
2. 删除冗余的css代码
3. css中相关的颜色控制代码改写成rgba

🎉 通过自定义代码实现server-status主题深色模式半透明样式的前置准备

---

README.md
script/install.sh
script/install_en.sh

installer: fix geo_check

---

resource/static/darkmode.css
resource/static/main.css
resource/static/theme-default/css/main.css
resource/static/theme-server-status/css/main.css
resource/template/theme-default/footer.html
resource/template/theme-default/header.html
resource/template/theme-default/home.html
resource/template/theme-default/network.html
resource/template/theme-server-status/footer.html
resource/template/theme-server-status/header.html
resource/template/theme-server-status/home.html
resource/template/theme-server-status/network.html

1.修复主box过宽导致的系列问题(移动端左右留空不一致等)
2.network页面适配深色模式和浅色模式
3.首页echarts自动适配深色浅色模式
4.修复default深色模式在ios设备不生效bug
1. network页面折线图取数逻辑优化，丢包率一直是100%时，不显示丢包markline线
2. 隐藏所有table横向滚动条
3. 关闭折线图hover效果，大幅提升echarts图表渲染速度
4. 移动端页底显示位置优化
https://dev.nezha.pp.ua

improve & fix : 主题优化及bug修复

---

resource/static/file.js
resource/template/dashboard-default/file.html

将下载的文件临时保存到 [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system)，写入完毕后再创建 Blob，避免下载大文件时长期占用内存。关闭 WebSSH 页面后会自动删除 OPFS 下所有文件
其它：
把下载进度条删了，没啥用

fm: store file to OPFS temporarily

---

resource/l10n/en-US.toml
resource/l10n/es-ES.toml
resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml
resource/template/component/nat.html
resource/template/dashboard-default/nat.html
resource/template/theme-angel-kanade/home.html
resource/template/theme-default/home.html

修复多CPU在默认主题和AngelKanade下显示的问题，完善内网穿透本地化文本。

fix cpu core display

---

resource/l10n/en-US.toml
resource/l10n/es-ES.toml
resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml
resource/static/theme-server-status/css/dark.css
resource/static/theme-server-status/css/light.css
resource/static/theme-server-status/css/main.css
resource/static/theme-server-status/js/mixin.js
resource/template/dashboard-default/server.html
resource/template/theme-server-status/header.html
resource/template/theme-server-status/home-group-false.html
resource/template/theme-server-status/home-group-true.html
resource/template/theme-server-status/home.html
resource/template/theme-server-status/menu.html

1. 首页通过在后台配置PublicNote字段，实现agent账单信息展示
2. 优化顶部导航，增加当前位置标识
3. 优化network页移动端样式
4. 优化后台server页展示，隐藏掉一些不重要的信息
5. 一些其他小优化
演示地址 https://dev.nezha.pp.ua/

feat: status-server主题增加agent账单信息展示

---

resource/template/theme-server-status/home-group-false.html
resource/template/theme-server-status/home-group-true.html
resource/template/theme-server-status/home.html

1. 支持价格和期限单独设置
2. 账单信息附加到group分组控制
3. 一些其他优化
演示地址 https://dev.nezha.pp.ua/

improve: status-server主题agent账单信息展示

---

README.md
script/install.sh
script/install_en.sh

make sure it will not interfere with other steps

installer: fix docker-compose detection logic

---

resource/l10n/en-US.toml
resource/l10n/es-ES.toml
resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml

一键安装这个词直接翻译成英文还是有点抽象，遂换成了另一种说法

chore: l10n: improve translation

---

resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml
resource/static/theme-server-status/css/dark.css
resource/static/theme-server-status/css/dark.plus.css
resource/static/theme-server-status/css/light.css
resource/static/theme-server-status/css/light.plus.css
resource/static/theme-server-status/css/main.css
resource/template/theme-server-status/footer.html
resource/template/theme-server-status/header.html
resource/template/theme-server-status/home-group-false.html
resource/template/theme-server-status/home-group-true.html
resource/template/theme-server-status/home.html

1. 首页账单信息：价格设置成“-1”前台展示为”PAYG“，自动续期（autoRenewal）功能增加支持付费周期yr,mo；
2. 当未获取到国旗图标时，默认彩虹旗；
3. 当未获取到os（操作系统）信息时，默认linux
4. 一些其他优化
账单信息配置说明： https://github.com/naiba/nezha/pull/425
演示地址 ：https://dev.nezha.pp.ua/

improve: status-server主题日常优化

---

cmd/dashboard/controller/member_api.go
model/ddns.go
pkg/ddns/webhook/webhook.go
resource/l10n/en-US.toml
resource/l10n/es-ES.toml
resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml
resource/static/main.js
resource/template/component/ddns.html

忘加了，加上这个才能使用webhook
另外重新加上了`#access_id#`和`#access_secret#`两个占位符

fix(ddns): add missing field WebhookRequestType

---

cmd/dashboard/controller/controller.go

do not check description file for theme-custom

---

README.md
script/install.ps1
script/install.sh
script/install_en.sh

更改部分代码使其符合sh语法，改进英文脚本部分翻译（比如panel->Dashboard）

installer: fix some style issues

---

README.md
script/install.sh
script/install_en.sh

sudo()的处理需要改下，之后有空再搞，现在先把命令的引号都去除了

fix installer

---

cmd/dashboard/controller/controller.go
cmd/dashboard/controller/ddns.go
cmd/dashboard/controller/jwt.go
cmd/dashboard/controller/server.go
cmd/dashboard/controller/server_group.go
cmd/dashboard/controller/ws.go
model/ddns.go

dev: add ddns create, edit and batch delete api

---

cmd/dashboard/main.go
cmd/dashboard/rpc/rpc.go

~~因h2c已经检查请求协议是否为http2了，去除了对`r.ProtoMajor == 2`的检查~~

add path check for multiplexer

---

cmd/dashboard/controller/alertrule.go
cmd/dashboard/controller/controller.go
cmd/dashboard/controller/cron.go
cmd/dashboard/controller/ddns.go
cmd/dashboard/controller/member_api.go
cmd/dashboard/controller/nat.go
cmd/dashboard/controller/notification.go
cmd/dashboard/controller/notification_group.go
cmd/dashboard/controller/server.go
model/alertrule.go
model/alertrule_api.go
model/cron.go
model/cron_api.go
model/ddns_api.go
model/nat_api.go
model/notification.go
model/notification_api.go
model/rule.go
service/singleton/alertsentinel.go
service/singleton/crontask.go
service/singleton/ddns.go
service/singleton/nat.go
service/singleton/notification.go
service/singleton/server.go

其它更改：init DB.Find操作直接写入全局List，不需要再Sort

add cron, nat api & refactor alert rule

---

resource/l10n/en-US.toml
resource/l10n/es-ES.toml
resource/l10n/zh-CN.toml
resource/l10n/zh-TW.toml
resource/static/theme-server-status/css/dark.css
resource/static/theme-server-status/css/light.css
resource/static/theme-server-status/css/light.plus.css
resource/static/theme-server-status/css/main.css
resource/template/theme-server-status/header.html
resource/template/theme-server-status/home-group-false.html
resource/template/theme-server-status/home-group-true.html
resource/template/theme-server-status/home.html
resource/template/theme-server-status/network.html

1. 首页通过在后台配置PublicNote字段，实现agent套餐信息展示
2. 未获取agent国家时,默认彩虹旗修改为联合国旗
3. 一些其他小优化
演示地址 https://dev.nezha.pp.ua/
配置教程：https://github.com/naiba/nezha/pull/425
效果图展示：

feat: status-server主题增加套餐信息展示

---

service/singleton/server.go

Fix https://github.com/nezhahq/nezha/issues/531

fix: allocate memory for geoip struct of new server instance

---

model/config.go
model/host.go

fix config default value

---

cmd/dashboard/main.go
model/config.go

feat: add listen_host

---

cmd/dashboard/controller/alertrule.go
cmd/dashboard/controller/controller.go
cmd/dashboard/controller/cron.go
cmd/dashboard/controller/ddns.go
cmd/dashboard/controller/nat.go
cmd/dashboard/controller/notification.go
cmd/dashboard/controller/server.go
cmd/dashboard/controller/service.go
model/common.go
model/server.go

Close https://github.com/nezhahq/nezha/issues/837
支持通过向各个 "list" api 后添加 id 参数来指定要获取的资源，可以指定多个
例如 `/server?id=1,2,3`

feat: support id query for "list" apis

---

cmd/dashboard/controller/controller.go

Return 404 status code if the requested path is not found

fix: return 404 when page not found

---

service/singleton/frontend-templates.yaml

feat: new theme nezha-ascii

---

.github/dependabot.yml

Revert "chore: setup dependabot"

---

cmd/dashboard/controller/controller.go
cmd/dashboard/controller/server.go
model/server_api.go
pkg/ddns/ddns.go
service/rpc/nezha.go
service/singleton/notification.go

https://github.com/nezhahq/agent/pull/165
Close https://github.com/nezhahq/nezha/issues/982

feat: batch set server config

---

.devcontainer/build.sh
.devcontainer/devcontainer.json

Add devcontainer related files to guide developers who want to participate quickly

chore: add devcontainer config

---

cmd/dashboard/rpc/rpc.go
model/server.go
service/singleton/servicesentinel.go
service/singleton/singleton.go

Close https://github.com/nezhahq/nezha/issues/1009

fix: ConfigCache not copied affer server updates

---

cmd/dashboard/controller/jwt.go
model/config.go

[是否能在docker compose中支持设置token过期时间？](https://github.com/nezhahq/nezha/issues/571)

feat: add configurable JWT timeout setting

---

model/alertrule.go
service/singleton/servicesentinel.go

fix service

---

cmd/dashboard/controller/setting.go
go.mod
go.sum
model/config.go
model/setting_api.go
pkg/utils/koanf.go
service/singleton/config.go
service/singleton/frontend-templates.yaml
service/singleton/singleton.go

fix: Save() does not work when updating config via HTTP API

fix: config fields not generated on first startup

---

cmd/dashboard/controller/setting.go
go.mod
model/config.go

Close https://github.com/nezhahq/nezha/issues/1023

hide install_host for guest

---

go.mod
go.sum
pkg/i18n/i18n.go
pkg/i18n/i18n_test.go
service/singleton/i18n.go

i18n: replace gettext implementation

---

Dockerfile

fix: embed tzdata to correct container timezone
